mysh: main.o parsecommand.o readcommand.o
	gcc -o mysh main.o parsecommand.o readcommand.o
main.o: main.c
	gcc -c main.c
parsecommand.o: parsecommand.c
	gcc -c parsecommand.c
readcommand.o: readcommand.c 
	gcc -c readcommand.c