myfilehide2: myfilehide2.o inputcheck.o
	gcc -o myfilehide2 myfilehide2.o inputcheck.o
myfilehide2.o: myfilehide2.c myheader.h
	gcc -c myfilehide2.c
inputcheck.o: inputcheck.c myheader.h
	gcc -c inputcheck.c