chkformatpw: main.o checklowercase.o checkuppercase.o checknumerical.o checkspecial.o
	gcc -o chkformatpw main.o checklowercase.o checkuppercase.o checknumerical.o checkspecial.o

main.o: main.c
	gcc -c main.c
checklowercase.o: checklowercase.c
	gcc -c checklowercase.c
checkuppercase.o: checkuppercase.c
	gcc -c checkuppercase.c
checknumerical.o: checknumerical.c
	gcc -c checknumerical.c
checkspecial.o: checkspecial.c
	gcc -c checkspecial.c
