mysh: main.o cprompt.o mem.o d.o grep.o
	gcc -o mysh main.o cprompt.o mem.o d.o grep.o
main.o: main.c
	gcc -c main.c
cprompt.o: cprompt.c
	gcc -c cprompt.c
mem.o: mem.c
	gcc -c mem.c
d.o: d.c 
	gcc -c d.c
grep.o: grep.c
	gcc -c grep.c